/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EncriptadorRSA;

import java.awt.Graphics;
import java.awt.HeadlessException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Miguel
 */
public final class EncripMensaje extends javax.swing.JFrame {

    int n, mod, numLambda, d;
    Map<String, Integer> mapKeyStr = new HashMap<>();
    int[] mensajeEncriptadoRSA;

    /**
     * Creates new form EncripMensaje
     */
    public EncripMensaje() {
        initComponents();
        this.setLocationRelativeTo(null);
        cifrasoRSA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtP = new javax.swing.JTextField();
        txtQ = new javax.swing.JTextField();
        lbPrimero = new javax.swing.JLabel();
        btnFijarPQ = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLtt1 = new javax.swing.JLabel();
        jCLambda = new javax.swing.JComboBox<>();
        btnFijarLambda = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLtt2 = new javax.swing.JLabel();
        txtLlavePublica = new javax.swing.JTextField();
        jLtt3 = new javax.swing.JLabel();
        jLtt4 = new javax.swing.JLabel();
        jcDLlave = new javax.swing.JComboBox<>();
        btnFIjarD = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtLlavePrivada = new javax.swing.JTextField();
        jLtt5 = new javax.swing.JLabel();
        jLtt6 = new javax.swing.JLabel();
        jLtt7 = new javax.swing.JLabel();
        txtMsgEncriptar = new javax.swing.JTextField();
        btnEncriparMensaje = new javax.swing.JButton();
        txtMensajeEncriptado = new javax.swing.JTextField();
        jLtt8 = new javax.swing.JLabel();
        txtMensajeEncriptadoClave = new javax.swing.JTextField();
        jLtt9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Encriptar mensaje");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel2)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Definir llave publica");

        lbPrimero.setForeground(new java.awt.Color(0, 0, 0));
        lbPrimero.setText("Escoja dos numeros primos");

        btnFijarPQ.setText("Fijar valores");
        btnFijarPQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFijarPQActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Q");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("P");

        jLtt1.setForeground(new java.awt.Color(0, 0, 0));
        jLtt1.setText("Escoja el numero lambda");
        jLtt1.setEnabled(false);

        jCLambda.setEnabled(false);
        jCLambda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLambdaActionPerformed(evt);
            }
        });

        btnFijarLambda.setText("Fijar numero");
        btnFijarLambda.setEnabled(false);
        btnFijarLambda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFijarLambdaActionPerformed(evt);
            }
        });

        jLtt2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLtt2.setForeground(new java.awt.Color(0, 0, 0));
        jLtt2.setText("Llave publica");

        jLtt3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLtt3.setForeground(new java.awt.Color(0, 0, 0));
        jLtt3.setText("Definir llave privada");
        jLtt3.setEnabled(false);

        jLtt4.setForeground(new java.awt.Color(0, 0, 0));
        jLtt4.setText("Escoja el numero d para la llave privada");
        jLtt4.setEnabled(false);

        jcDLlave.setEnabled(false);

        btnFIjarD.setText("Fijar d");
        btnFIjarD.setEnabled(false);
        btnFIjarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFIjarDActionPerformed(evt);
            }
        });

        txtLlavePrivada.setEditable(false);
        txtLlavePrivada.setEnabled(false);

        jLtt5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLtt5.setForeground(new java.awt.Color(0, 0, 0));
        jLtt5.setText("Llave privada");
        jLtt5.setEnabled(false);

        jLtt6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLtt6.setForeground(new java.awt.Color(0, 0, 0));
        jLtt6.setText("Encriptar ");
        jLtt6.setEnabled(false);

        jLtt7.setForeground(new java.awt.Color(0, 0, 0));
        jLtt7.setText("Mensaje para encriptar");
        jLtt7.setEnabled(false);

        txtMsgEncriptar.setEnabled(false);

        btnEncriparMensaje.setText("Encriptar");
        btnEncriparMensaje.setEnabled(false);
        btnEncriparMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncriparMensajeActionPerformed(evt);
            }
        });

        txtMensajeEncriptado.setEditable(false);
        txtMensajeEncriptado.setEnabled(false);

        jLtt8.setForeground(new java.awt.Color(0, 0, 0));
        jLtt8.setText("Mensaje encriptado RSA");
        jLtt8.setEnabled(false);

        txtMensajeEncriptadoClave.setEditable(false);
        txtMensajeEncriptadoClave.setEnabled(false);

        jLtt9.setForeground(new java.awt.Color(0, 0, 0));
        jLtt9.setText("Mensaje encriptado con clave");
        jLtt9.setEnabled(false);

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Fijar llave publica");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("*Recuerde fijar este dato si esta creando su llave");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("*Si ya tiene una llave publica, solo ingresela y");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("omita lo anterior");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLtt1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCLambda, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFijarLambda)
                            .addComponent(jLabel5)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLtt2)
                                .addGap(18, 18, 18)
                                .addComponent(txtLlavePublica, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLtt6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(190, 190, 190)
                        .addComponent(jLtt3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(5, 5, 5)
                                .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFijarPQ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLtt4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcDLlave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFIjarD)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLtt5)
                                .addGap(18, 18, 18)
                                .addComponent(txtLlavePrivada, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLtt9)
                            .addComponent(jLtt7))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLtt8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMensajeEncriptadoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMsgEncriptar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMensajeEncriptado, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncriparMensaje)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLtt3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrimero)
                    .addComponent(jLtt4)
                    .addComponent(jcDLlave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(btnFIjarD))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFijarPQ)
                            .addComponent(jLtt5)
                            .addComponent(txtLlavePrivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLtt1)
                            .addComponent(jCLambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLtt6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(btnFijarLambda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMsgEncriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLtt7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEncriparMensaje)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMensajeEncriptado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLtt8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMensajeEncriptadoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLtt9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLlavePublica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLtt2))
                        .addGap(28, 28, 28)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFijarPQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFijarPQActionPerformed
        try {
            if (nprimo(Integer.parseInt(txtP.getText())) && nprimo(Integer.parseInt(txtQ.getText()))) {
                jLtt1.setEnabled(true);
                jCLambda.setEnabled(true);
                btnFijarLambda.setEnabled(true);
                n = Integer.parseInt(txtP.getText()) * Integer.parseInt(txtQ.getText());
                ComprobarInverso();
            } else {
                JOptionPane.showMessageDialog(null, "Los numeros que digite tienen que ser primos, intentelo de nuevo", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Los numeros que digite tienen que ser enteros primos positivos, intentelo de nuevo", "Error", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException headlessException) {
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnFijarPQActionPerformed

    private void btnFijarLambdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFijarLambdaActionPerformed
        jLtt2.setEnabled(true);
        jLtt3.setEnabled(true);
        jLtt4.setEnabled(true);
        btnFIjarD.setEnabled(true);
        txtLlavePublica.setEnabled(true);
        jcDLlave.setEnabled(true);

        numLambda = Integer.parseInt((String) jCLambda.getSelectedItem());
        txtLlavePublica.setText("(" + n + ", " + numLambda + ")");
        comprobarLLavePrivada();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFijarLambdaActionPerformed

    private void btnFIjarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFIjarDActionPerformed
        d = Integer.parseInt((String) jcDLlave.getSelectedItem());
        jLtt5.setEnabled(true);
        jLtt6.setEnabled(true);
        jLtt7.setEnabled(true);
        txtMsgEncriptar.setEnabled(true);
        btnEncriparMensaje.setEnabled(true);
        txtLlavePrivada.setEnabled(true);
        txtLlavePrivada.setText("(" + n + ", " + d + ")");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFIjarDActionPerformed

    private void btnEncriparMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncriparMensajeActionPerformed
        String[] letrasMensaje = txtMsgEncriptar.getText().toUpperCase().split("");
        String mensajeRSA = "";
        String mensajeCodificado = "";
        jLtt8.setEnabled(true);
        jLtt9.setEnabled(true);
        txtMensajeEncriptado.setEnabled(true);
        txtMensajeEncriptadoClave.setEnabled(true);
        mensajeEncriptadoRSA = new int[letrasMensaje.length];
        for (int i = 0; i < letrasMensaje.length; i++) {
            mensajeEncriptadoRSA[i] = mapKeyStr.get(letrasMensaje[i]);
            mensajeRSA = mensajeRSA + mapKeyStr.get(letrasMensaje[i]) + " - ";
        }
        txtMensajeEncriptado.setText(mensajeRSA);

        for (int j = 0; j < mensajeEncriptadoRSA.length; j++) {
            mensajeCodificado += generarInversoElevado(mensajeEncriptadoRSA[j]) + " - ";
            txtMensajeEncriptadoClave.setText(mensajeCodificado);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncriparMensajeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        EncripMensaje ms = new EncripMensaje();
        ms.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Index ini = new Index();
        ini.setVisible(true);
        ini.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String[] numeros = txtLlavePublica.getText().replaceAll(" ", "").replaceAll(",", "-").split("-");
            n = Integer.parseInt(numeros[0]);
            numLambda = Integer.parseInt(numeros[1]);
            jLtt6.setEnabled(true);
            jLtt7.setEnabled(true);
            txtMsgEncriptar.setEnabled(true);
            btnEncriparMensaje.setEnabled(true);
        } catch (IndexOutOfBoundsException arrayError) {
            JOptionPane.showMessageDialog(null, "Tiene que ingresar dos valores enteros positivos separados por una coma, intentelo de nuevo");
        } catch(NumberFormatException numberFormatException){
            JOptionPane.showMessageDialog(null, "En la llave publica tiene que ingresar dos numeros enteros positivos, intentelo de nuevo");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCLambdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLambdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLambdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncripMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncripMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncripMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncripMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncripMensaje().setVisible(true);
            }
        });
    }
    //metodo para comprobar si el numero que se le da como parametro es primo.
    public boolean nprimo(int n) {
        int div = 0;
        for (int i = 1; i <= n; i++) {
            if (n % i == 0) {
                div++;
            }
        }
        return div <= 2;
    }
    
    public void ComprobarInverso() {
        mod = (Integer.parseInt(txtQ.getText())  - 1) * (Integer.parseInt(txtP.getText()) - 1);
        int answ;

        for (int a = 1; a < mod; a++) {
            for (int i = 1; i < mod; i++) {
                
                answ = (a * i) % mod;
                if (answ == 1) {
                    jCLambda.addItem(String.valueOf(a));
                }
            }
        }

    }

    public void comprobarLLavePrivada() {
        for (int i = 0; i < mod; i++) {
            if ((i * numLambda) % mod == 1) {
                jcDLlave.addItem(String.valueOf(i));
            }
        }
    }
    //metodo para introducir en mapKey el alfabeto utilizando el codigo ASCII cuya representacion de las letras equivalen a los numeros
    //del 65 al 90 y cuando se parsea a char, se obtienen las letras del alfabeto.
    public void cifrasoRSA() {
        char letra;
        mapKeyStr.put(" ", 9);
        for (int i = 0; i < 26; i++) {
            letra = (char) (i + 65);
            mapKeyStr.put(String.valueOf(letra), i + 10);
        }
    }
    //metodo para el proceso de elevar el numero que recibe como parametro al lambda, 
    //la funcion es reducir la potencia(en este caso el lambda) para que esta no sea muy elevada y rompa el programa
    public int generarInversoElevado(int numero) {
        int limite, respuesta, aux;
        if (numLambda >= 5) {
            limite = numLambda / 2;
            respuesta = (int) Math.pow(numero, 2);
            aux = (respuesta % n); 
            respuesta = aux;
            for (int i = 0; i < (limite) - 2; i++) { 
                respuesta = (respuesta * aux) % n;
            }
            respuesta = (respuesta * ((aux * numero) % n)) % n;
        } else {
            return (int) ((Math.pow(numero, numLambda)) % n);
        }
        return (int) respuesta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncriparMensaje;
    private javax.swing.JButton btnFIjarD;
    private javax.swing.JButton btnFijarLambda;
    private javax.swing.JButton btnFijarPQ;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCLambda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLtt1;
    private javax.swing.JLabel jLtt2;
    private javax.swing.JLabel jLtt3;
    private javax.swing.JLabel jLtt4;
    private javax.swing.JLabel jLtt5;
    private javax.swing.JLabel jLtt6;
    private javax.swing.JLabel jLtt7;
    private javax.swing.JLabel jLtt8;
    private javax.swing.JLabel jLtt9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> jcDLlave;
    private javax.swing.JLabel lbPrimero;
    private javax.swing.JTextField txtLlavePrivada;
    private javax.swing.JTextField txtLlavePublica;
    private javax.swing.JTextField txtMensajeEncriptado;
    private javax.swing.JTextField txtMensajeEncriptadoClave;
    private javax.swing.JTextField txtMsgEncriptar;
    private javax.swing.JTextField txtP;
    private javax.swing.JTextField txtQ;
    // End of variables declaration//GEN-END:variables
}
